//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 08:59:54 PM CET 
//


package com.schibsted.test.webapp.controller.flowconfig.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="forward" type="{http://webapp.test.schibsted.com/controller/flowconfig/beans}Forward" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="businessActionClass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="authenticated" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="accesRole" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="httpMethod" use="required" type="{http://webapp.test.schibsted.com/controller/flowconfig/beans}HttpMethod" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessAction", propOrder = {
    "forward"
})
public class BusinessAction {

    @XmlElement(required = true)
    protected List<Forward> forward;
    @XmlAttribute(name = "path", required = true)
    protected String path;
    @XmlAttribute(name = "businessActionClass", required = true)
    protected String businessActionClass;
    @XmlAttribute(name = "authenticated", required = true)
    protected boolean authenticated;
    @XmlAttribute(name = "accesRole")
    protected String accesRole;
    @XmlAttribute(name = "httpMethod", required = true)
    protected HttpMethod httpMethod;

    /**
     * Gets the value of the forward property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forward property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForward().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Forward }
     * 
     * 
     */
    public List<Forward> getForward() {
        if (forward == null) {
            forward = new ArrayList<Forward>();
        }
        return this.forward;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the businessActionClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessActionClass() {
        return businessActionClass;
    }

    /**
     * Sets the value of the businessActionClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessActionClass(String value) {
        this.businessActionClass = value;
    }

    /**
     * Gets the value of the authenticated property.
     * 
     */
    public boolean isAuthenticated() {
        return authenticated;
    }

    /**
     * Sets the value of the authenticated property.
     * 
     */
    public void setAuthenticated(boolean value) {
        this.authenticated = value;
    }

    /**
     * Gets the value of the accesRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccesRole() {
        return accesRole;
    }

    /**
     * Sets the value of the accesRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccesRole(String value) {
        this.accesRole = value;
    }

    /**
     * Gets the value of the httpMethod property.
     * 
     * @return
     *     possible object is
     *     {@link HttpMethod }
     *     
     */
    public HttpMethod getHttpMethod() {
        return httpMethod;
    }

    /**
     * Sets the value of the httpMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpMethod }
     *     
     */
    public void setHttpMethod(HttpMethod value) {
        this.httpMethod = value;
    }

}
